CV2-5778-change-language-detection-agreement
meedan/alegre pull request #474
Opened 2024-12-19 16:00 UTC by ahmednasserswe

…TH of them is more than "Threshold" confident`

lowering threshold to 0.7

## Description
implementing this strategy to use google language detection api 
Both CLD3 and FastText must agree and BOTH of them is more than "Threshold" confident
Threshold here is 0.7 
Practically, in this PR, we only lower the threshold from 0.9 to 0.7

Reference: CV2-5367 (to provide additional context)

## How has this been tested?
unittests

2024-12-20 10:01 UTC, computermacgyver requested changes
Can you please address the Sentry error that has been tagged on this PR?

It occurs when one of the confidence scores is `None`. We can avoid this by removing the `min_confidence=` line and putting this directly in the `if` statement alongside a check that one of the values is not `None`

2025-01-05 11:32 UTC, computermacgyver approved these changes

2025-01-06 10:35 UTC, skyemeedan reviewed
Logic looks great!  can you please clean up the comments a bit so it will not be confusing next time we look at this code?

2025-01-06 10:35 UTC, skyemeedan commented on app/main/lib/langid.py
>      # max_confidence = max(fasttext_result['result']['confidence'], cld_result['result']['confidence'])
please remove the disabled versions of the code, unless there is a reason we need to keep it around, in which case please add a comment to explain why

2025-01-06 10:35 UTC, skyemeedan commented on app/main/lib/langid.py
> +            and  min(fasttext_result['result']['confidence'], cld_result['result']['confidence']) >= 0.7:
Can you add a commented with the currently expected behavior `Both CLD3 and FastText must be have non-null confidence scores, agree on language tag, and BOTH of them is more than "Threshold" confident` and the link to the artifact where the decision was made about the 0.7 threshold value?  I think that is: https://meedan.atlassian.net/browse/CV2-5367

2025-01-06 10:35 UTC, skyemeedan commented on app/main/lib/langid.py
>        # Now - FastText and CLD agree AND BOTH are more than 90% confident
I think these comments not needed anymore?

2025-01-08 16:45 UTC, skyemeedan approved these changes

2025-01-08 18:56 UTC, merged